version: "3.9"

services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: containers/typescript/Dockerfile
    volumes:
      - ./application:/application
      - front_node_modules:/application/node_modules
    tty: true
volumes:
  front_node_modules:
